version: '3.8'

services:
  # ==================== REDIS ====================
  redis:
    image: redis:7-alpine
    container_name: sharedmelody_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_secure_password_123
    networks:
      - sharedmelody_network

  # ==================== BACKEND ====================
  backend:
    build: ./backend
    container_name: sharedmelody_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      FRONTEND_URL: https://sharedmelody.com
      DB_HOST: 154.12.227.234
      DB_PORT: 5432
      DB_NAME: sharedmelody_db
      DB_USER: postgresroot
      DB_PASSWORD: 69dMb7HBjJLL
      DB_SSL: "false"
      DB_SSLMODE: "disable"
      JWT_SECRET: shared-melody-super-secret-jwt-key-2024
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_SECRET: shared-melody-super-secret-refresh-key-2024
      JWT_REFRESH_EXPIRES_IN: 7d
      GOOGLE_CLIENT_ID: 191069086328-ih31gmnmqq5sl2134dumg7ff0h8bnfbo.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      MICROSOFT_CLIENT_ID: "DISABLED"
      MICROSOFT_CLIENT_SECRET: "DISABLED"
      APPLE_CLIENT_ID: "DISABLED"
      APPLE_TEAM_ID: "DISABLED"
      APPLE_KEY_ID: "DISABLED"
      APPLE_PRIVATE_KEY_PATH: "DISABLED"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_secure_password_123
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - sharedmelody_network

  # ==================== FRONTEND ====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sharedmelody_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://api.sharedmelody.com/api
      - REACT_APP_APP_NAME=SharedMelody
    restart: always
    networks:
      - sharedmelody_network

networks:
  sharedmelody_network:
    driver: bridge
