version: '3.8'

services:
  # ==================== REDIS ====================
  redis:
    image: redis:7-alpine
    container_name: sharedmelody_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_secure_password_123
    networks:
      - sharedmelody_network

  # ==================== BACKEND ====================
  backend:
    build: ./backend
    container_name: sharedmelody_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - sharedmelody_network

  # ==================== FRONTEND ====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sharedmelody_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production
    restart: always
    networks:
      - sharedmelody_network

networks:
  sharedmelody_network:
    driver: bridge
